package utils;

public enum Commands {
	SELECT_DEVICE, TURN_ON, TURN_OFF, EXIT, SET_NETWORK_INFO, SET_PORT, 
	SET_SERVER_IP, SET_SERVER_PORT, SENSOR_ON, SENSOR_OFF,
	GET_STATUS, INFORM_STATUS, HELP;
}
